version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    restart: unless-stopped
    container_name: student_fita_nginx
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - php
      - mysql
      - composer
      - npm
    networks:
      - laravel
  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: student_fita_php
    ports:
      - ":9000"
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - .env:/var/www/html/.env
    networks:
      - laravel
  mysql:
    image: mysql:8.0.29
    container_name: student_fita_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - .env:/var/www/html/.env
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: student_fita_composer
    volumes:
      - .:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-laravel} #system user
    profiles: [ "composer" ]
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel
  artisan:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-laravel}
    container_name: artisan
    volumes:
      - .:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - mysql
    working_dir: /var/www/html
    profiles: [ "artisan" ]
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel
  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - .:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - "3000:3000"
      - "3001:3001"
    working_dir: /var/www/html
    profiles: [ "npm" ]
    entrypoint: [ 'npm' ]
    networks:
      - laravel
#student_fita_server:
#  build: .
#  dockerfile: ./docker/Dockerfile
#  container_name: student_fita_server
#  working_dir: /var/www/html
#  ports:
#    - "80:80"
#  volumes:
#    - .:/var/www/html
#    - ./docker/nginx_log:/var/log/nginx
#    - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
#    - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
#  links:
#    - mysql
#mysql:
#  image: mysql:8.0.29
#  container_name: student_fita_mysql
#  ports:
#    - "3308:3306"
#  volumes:
#    - ./docker/mysql:/var/lib/mysql
#  environment:
#    MYSQL_ROOT_PASSWORD: password
