export enum AuthStudentMutationTypes {
    SET_LOGIN_STATUS_STUDENT = 'SET_LOGIN_STATUS_STUDENT',
    SET_AUTH_USER_STUDENT = 'SET_AUTH_USER_STUDENT',
    SET_ACCESS_TOKEN_STUDENT = 'SET_ACCESS_TOKEN_STUDENT',
}
